version: '3.7'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    #ports:
      #- 8000:8000
    env_file: .env
    depends_on:
      - db
    #volumes:
      #- ./app:/code
      #- static:/code/static
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  nginx:
    build: ./nginx
    hostname: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    #volumes:
      #- ./config/nginx:/etc/nginx/conf.d
      #- static:/code:ro

volumes:
  postgres_data:
  static:
